#
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/zjut-training?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
#    username: root
#    password: password
#    driver-class-name: com.mysql.cj.jdbc.Driver

#spring:
#  datasource:
#    url: jdbc:mysql://training-system-mysql:3306/zjut-training?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
#    username: root
#    password: 123321
#    driver-class-name: com.mysql.cj.jdbc.Driver